[package]
name = "openscreen-common"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytes = { version = "1", default-features = false }
heapless = "0.8"

[lints]
workspace = true
