[package]
name = "openscreen-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
heapless = { workspace = true }

[lints]
workspace = true
